src/Entity/UserAddress.php
<?php

namespace App\Entity;

use App\Repository\UserAddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserAddressRepository::class)]
class UserAddress
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    private ?string $address = null;

    #[ORM\Column(length: 10)]
    #[Assert\NotBlank()]
    private ?string $zip_code = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    private ?string $city = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'userAddresses')]
    private Collection $user;

    /**
     * @var Collection<int, Devis>
     */
    #[ORM\OneToMany(targetEntity: Devis::class, mappedBy: 'address')]
    private Collection $devis;

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->devis = new ArrayCollection();
    }

    public function __toString(): string {
        return "$this->address $this->zip_code $this->city";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): static
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): static
    {
        if (!$this->user->contains($user)) {
            $this->user->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        $this->user->removeElement($user);

        return $this;
    }

    /**
     * @return Collection<int, Devis>
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }

    public function addDevi(Devis $devi): static
    {
        if (!$this->devis->contains($devi)) {
            $this->devis->add($devi);
            $devi->setAddress($this);
        }

        return $this;
    }

    public function removeDevi(Devis $devi): static
    {
        if ($this->devis->removeElement($devi)) {
            // set the owning side to null (unless already changed)
            if ($devi->getAddress() === $this) {
                $devi->setAddress(null);
            }
        }

        return $this;
    }
}

src/Controller/Backend/AvisController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Avis;
use App\Entity\Filtres\AvisFilter;
use App\Entity\User;
use App\Form\Backend\Filtres\SearchAvisType;
use App\Form\Frontend\UserAvisFormType;
use App\Repository\AvisRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class AvisController extends AbstractController
{
    public function __construct(
        private Security $security,
        private EntityManagerInterface $em,
        private AvisRepository $avisRepository,
    ) {
    }

    #[Route('admin/avis', name: 'admin_avis_index', methods: ['GET'])]
    public function manage(): Response
    {

        $avis = $this->avisRepository->findAll();

        return $this->render('Backend/Avis/index.html.twig', [
            'avis' => $avis,
        ]);
    }

    #[Route('admin/avis/{id}/delete', name: 'admin_avis_delete', methods: ['POST'])]
    public function delete(Request $request, Avis $avis): Response
    {
        if (!$avis) {
            $this->addFlash('danger', 'Avis introuvable');

            return $this->redirectToRoute('admin_avis_index');
        }

        if ($this->isCsrfTokenValid('delete' . $avis->getId(), $request->request->get('token'))) {
            $this->em->remove($avis);
            $this->em->flush();

            $this->addFlash('success', 'Avis supprimé avec succès !');
        } else {
            $this->addFlash('danger', 'Token invalide');
        }

        return $this->redirectToRoute('admin_avis_index');
    }
}

src/Controller/Backend/CategorieController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Categorie;
use App\Entity\Filtres\CategorieFilter;
use App\Form\Backend\CategorieFormType;
use App\Form\Backend\Filtres\SearchCategorieType;
use App\Repository\CategorieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/categories', name: 'admin_categories')]
class CategorieController extends AbstractController
{
    public function __construct(
        private EntityManagerInterface $em,
        private CategorieRepository $categorieRepo,
    ) {
    }

    #[Route('', name: '_index', methods:['GET'])]
    public function index(Request $request): Response
    {
        $data = new CategorieFilter();

        $data->setPage($request->get('page', 1));
        $data->setLimit($request->get('limit', 10));

        $form = $this->createForm(SearchCategorieType::class, $data);
        $form->handleRequest($request);

        $categories = $this->categorieRepo->findCategorieData($data);

        return $this->render('Backend/Categorie/index.html.twig', [
            'categories' => $categories,
            'form' => $form,
        ]);
    }

    #[Route('/create', name: '_create', methods: ['GET', 'POST'])]
    public function create(Request $request): Response
    {   
        $user = $this->getUser();
        $categorie = new Categorie();
        $categorie->setUser($user);
        
        if (!$user) {
            $this->addFlash('danger', 'Vous devez être connecté pour créer une catégorie');

            return $this->redirectToRoute('app_login');
        }

        $form = $this->createForm(CategorieFormType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($categorie);
            $this->em->flush();

            $this->addFlash('success', 'Categorie crée avec succès !');

            return $this->redirectToRoute('admin_categories_index');
        }

        return $this->render('Backend/Categorie/create.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{slug}/update', name: '_update', methods: ['POST', 'GET'])]
    public function update(Request $request, Categorie $categorie): Response
    {
        if (!$categorie) {
            $this->addFlash('danger', 'Catégorie introuvable');

            $this->redirectToRoute('admin_categories_index');
        }

        $form = $this->createForm(CategorieFormType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($categorie);
            $this->em->flush();

            $this->addFlash('success', 'Catégorie modifiée avec succès !');

            return $this->redirectToRoute('admin_categories_index');
        }

        return $this->render('Backend/Categorie/update.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name:'_delete', methods:['POST'])]
    public function delete(Request $request, Categorie $categorie): Response {
        if (!$categorie) {
            $this->addFlash('danger', 'Categorie introuvable');

           return $this->redirectToRoute('admin_categorie_index');
        } 

        if ($this->isCsrfTokenValid('delete' . $categorie->getId(), $request->request->get('token'))) {
            $this->em->remove($categorie);
            $this->em->flush();

            $this->addFlash('success', 'Categorie supprimée avec succès !');
        } else {
            $this->addFlash('danger', 'Token invalide');
        }

        return $this->redirectToRoute('admin_categories_index');
    }
}

src/Controller/Backend/LogsController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Filtres\DevisLogsFilter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use App\Form\Backend\Filtres\SearchDevisLogsType;
use App\Repository\DevisLogsRepository;

class LogsController extends AbstractController
{
    public function __construct(
        private DevisLogsRepository $devisLogsRepository,
    ){}

    #[IsGranted('ROLE_SUPER_ADMIN')]
    #[Route('admin/logs', name: 'admin_logs_index')]
    public function index(Request $request): Response
    {   
        $data = new DevisLogsFilter;

        $data->setPage($request->get('page', 1));
        $data->setLimit($request->get('limit', 10));

        $form = $this->createForm(SearchDevisLogsType::class, $data);
        $form->handleRequest($request);

        $devisLogs = $this->devisLogsRepository->findDevisLogsData($data);

        $user = $this->getUser();

        if (!$user) {
            $this->addFlash('danger', 'Vous devez être connecté pour accéder à cette page.');

            return $this->redirectToRoute('app_login');
        }

        if (!$this->isGranted('ROLE_SUPER_ADMIN')) {
            $this->addFlash('danger', 'Vous n\'avez pas l\'autorisation pour accéder à cette page.');

            return $this->redirectToRoute('admin_users_index');
        }

        return $this->render('Backend/Logs/index.html.twig', [
            'devisLogs' => $devisLogs,
            'form' => $form,
        ]);
    }
}

src/Controller/Backend/RealisationController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Filtres\RealisationFilter;
use App\Entity\Realisation;
use App\Form\Backend\Filtres\SearchRealisationType;
use App\Form\Backend\RealisationFormType;
use App\Repository\RealisationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/realisations', name:'admin_realisations')]
class RealisationController extends AbstractController
{   
    public function __construct(
        private EntityManagerInterface $em,
        private RealisationRepository $realisationRepository,
    ){}

    #[Route('', name: '_index', methods: ['GET'])]
    public function index(Request $request): Response
    {   
        $data = new RealisationFilter();

        $data->setPage($request->get('page', 1));
        $data->setLimit($request->get('limit', 10));

        $form = $this->createForm(SearchRealisationType::class, $data);
        $form->handleRequest($request);

        $realisations = $this->realisationRepository->findRealisationData($data);

        return $this->render('Backend/Realisation/index.html.twig', [
            'realisations' => $realisations,
            'form' => $form,
        ]);
    }

    #[Route('/create', name: '_create', methods: ['GET', 'POST'])]
    public function create(Request $request): Response
    {
        $user = $this->getUser();
        $realisation = new Realisation();

        $realisation->setUser($user);
        

        if (!$user) {
            $this->addFlash('danger', 'Vous devez être connecté pour créer une réalisation');

            return $this->redirectToRoute('app_login');
        }

        $form = $this->createForm(RealisationFormType::class, $realisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($realisation);
            $this->em->flush();

            $this->addFlash('success', 'Réalisation crée avec succès !');

            return $this->redirectToRoute('admin_realisations_index');
        }

        return $this->render('Backend/Realisation/create.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{slug}/update', name: '_update', methods: ['POST', 'GET'])]
    public function update(Request $request, Realisation $realisation): Response
    {
        if (!$realisation) {
            $this->addFlash('danger', 'Réalisation introuvable');

            $this->redirectToRoute('admin_realisations_index');
        }

        $form = $this->createForm(RealisationFormType::class, $realisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($realisation);
            $this->em->flush();

            $this->addFlash('success', 'Réalisation modifiée avec succès !');

            return $this->redirectToRoute('admin_realisations_index');
        }

        return $this->render('Backend/Realisation/update.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name:'_delete', methods:['POST'])]
    public function delete(Request $request, Realisation $realisation): Response {
        if (!$realisation) {
            $this->addFlash('danger', 'Réalisation introuvable');

           return $this->redirectToRoute('admin_realisations_index');
        } 

        if ($this->isCsrfTokenValid('delete' . $realisation->getId(), $request->request->get('token'))) {
            $this->em->remove($realisation);
            $this->em->flush();

            $this->addFlash('success', 'Réalisation supprimée avec succès !');
        } else {
            $this->addFlash('danger', 'Token invalide');
        }

        return $this->redirectToRoute('admin_realisations_index');
    }
}

src/Controller/Backend/RegistrationController.php
<?php

namespace App\Controller\Backend;

use App\Entity\User;
use App\Form\RegistrationFormType;
use App\Security\EmailVerifier;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mime\Address;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use SymfonyCasts\Bundle\VerifyEmail\Exception\VerifyEmailExceptionInterface;

class RegistrationController extends AbstractController
{
    public function __construct(private EmailVerifier $emailVerifier)
    {
    }

    #[Route('/register', name: 'app_register')]
    public function register(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager->persist($user);
            $entityManager->flush();

            // generate a signed url and email it to the user
            $this->emailVerifier->sendEmailConfirmation('app_verify_email', $user,
                (new TemplatedEmail())
                    ->from(new Address('anthony.koenig.testing@outlook.com', 'No-reply-cct-tolerie'))
                    ->to($user->getEmail())
                    ->subject('Please Confirm your Email')
                    ->htmlTemplate('registration/confirmation_email.html.twig')
            );

            // do anything else you need here, like send an email
            $this->addFlash('success', 'Veuillez vérifier votre adresse email pour continuer');

            return $this->redirectToRoute('app_app');
        }

        return $this->render('registration/register.html.twig', [
            'registrationForm' => $form,
        ]);
    }

    #[Route('/verify/email', name: 'app_verify_email')]
    public function verifyUserEmail(Request $request, TranslatorInterface $translator): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // validate email confirmation link, sets User::isVerified=true and persists
        try {
            $this->emailVerifier->handleEmailConfirmation($request, $this->getUser());
        } catch (VerifyEmailExceptionInterface $exception) {
            $this->addFlash('verify_email_error', $translator->trans($exception->getReason(), [], 'VerifyEmailBundle'));

            return $this->redirectToRoute('app_register');  
        }

        // @TODO Change the redirect on success and handle or remove the flash message in your templates
        
        $this->addFlash('success', 'Votre email à été verifié !');
        
        return $this->redirectToRoute('app_app');
    }
}

templates/Backend/Devis/index.html.twig
{% extends 'Backend/base.html.twig' %}

{% block title %}
	{{parent()}}
	Devis
{% endblock %}

{% block body %}
	<section class="container">
		<div class="container text-center">
			<h1 class="text-center">Administration des demande de devis</h1>
		</div>
		<div class="dropdown-management">
			<div class="container admin-filter">
				<button class="admin-filter-button" data-controller="user-filter">Filtrer<i class="bi bi-filter-right"></i>
				</button>
				{% include 'Backend/Devis/Components/Filters/_devisFilter.html.twig' %}
			</div>
			<div class="container admin-pagination dropdown-pagination">
				<button class="admin-filter-button" {{ stimulus_controller('user-pagination')}}>Trier /
					{{ devis.getTotalItemCount }}
					{{ devis.getTotalItemCount > 1 ? 'Devis' : 'devis'}}<i class="bi bi-sort-alpha-down-alt"></i>
				</button>
				{% include 'Backend/Devis/Components/Pagination/_devisSortable.html.twig' %}
			</div>
		</div>
		<div class="container-pages-management">
			<div>
				{{ knp_pagination_render(devis) }}
			</div>
			<ul>
				<li>
					<ahref="{{path('admin_devis_index',app.request.query.all|merge({limit:10}))}}">10</ahref=>
				</li>
				<li>
					<ahref="{{path('admin_devis_index',app.request.query.all|merge({limit:25}))}}">25</ahref=>
				</li>
				<li>
					<ahref="{{path('admin_devis_index',app.request.query.all|merge({limit:50}))}}">50</ahref=>
				</li>
				<li>
					<ahref="{{path('admin_devis_index',app.request.query.all|merge({limit:100}))}}">100</ahref=>
				</li>
			</ul>
		</div>
		<div class="container wrapper-devis">
			{% for devi in devis %}
				<div class="card-admin">
					<div class="card-admin-header">
						{% if devi.devisImages|length > 0 %}
							<div class="swiper" {{ stimulus_controller('carousel') }}>
								<div class="swiper-wrapper">
									{% for image in devi.devisImages %}
										<div class="swiper-slide">
											<img src="{{ vich_uploader_asset(image)}}" alt="">
										</div>
									{% endfor %}
								</div>
								<div class="swiper-button-prev"></div>
								<div class="swiper-button-next"></div>
							</div>
						{% endif %}
					</div>
					<div class="card-admin-content">
						<div class="card-admin-content-description">
							<div class="card-admin-content-description-title">
								<h3>
									Informations devis
								</h3>
							</div>
							<div class="card-admin-content-informations">
								<div class="left">
									<div>
										<p class="bold">Prénom et nom</p>
									</div>
									<div>
										<p>{{devi.firstName}}
											{{devi.lastName}}</p>
									</div>
									<div>
										<p class="bold">Email</p>
									</div>
									<div>
										<p>{{devi.user.email}}</p>
									</div>
									<div>
										<p class="bold">Adresse</p>
										<p>{{devi.address.address}}</p>
										<p>{{devi.address.zipCode}}</p>
										<p>{{devi.address.city}}</p>
									</div>
									<div>
										<p class="bold">Création</p>
										<p>{{devi.createdAt|date("d-m-Y H:i:s")}}</p>
									</div>
								</div>
								<div class="right">
									<div>
										<p class="bold">Status</p>
										{% if devi.status == "En attente" %}
											<p class="border-grey border">{{devi.status}}</p>
										{% elseif devi.status == "Accepté" %}
											<p class="border-yellow border">{{devi.status}}</p>
										{% elseif devi.status == "Terminé" %}
											<p class="border-green border">{{devi.status}}</p>
										{% elseif devi.status == "Annulé" %}
											<p class="border-orange border">{{devi.status}}</p>
											<p>Annulé par {{ devi.canceledBy == 'admin' ? 'un administrateur' : 'le client' }}</p>
										{% else %}
											<p class="border-red border">{{devi.status}}</p>
										{% endif %}
										<p>
											<a href="{{ path('admin_devis_update', {id: devi.id}) }}" id="devis-btn" class="button button-update">Modifier</a>
										</p>
									</div>
									<div>
										<p class="bold">Titre</p>
										<p>{{devi.name}}</p>
									</div>
									<div>
										<p class="bold">Description</p>
										<p>{{devi.description}}</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</section>
{% endblock %}

templates/Backend/Devis/update.html.twig
{% extends 'Backend/base.html.twig' %}

{% block title %}
	{{ parent() }}
	Modifier le status d'un devis
{% endblock %}

{% block body %}
		<div class="container">
			<h1 class="text-center">Modifier un devis</h1>

			{{ form_start(form, {attr: {class: 'form-width form-margin-bottom-admin', 'data-controller': 'modal'}}) }}
			{{ form_errors(form) }}
			<div class="form-group">
				{{ form_row(form.status) }}
			</div>
			<div class="form-label-input text-center">
				<button type="submit" class="button button-update">Modifier</button>
			</div>
			{{ form_end(form) }}
		</div>
		<div class="form-label-input text-center">
			<a href="{{ path('admin_devis_index') }}" class="button button-return">Retour aux devis</a>
		</div>
{% endblock %}